export const WS_AUTH_CONNECTION_START = "WS_AUTH_CONNECTION_START";
export const WS_AUTH_CONNECTION_SUCCESS = "WS_AUTH_CONNECTION_SUCCESS";
export const WS_AUTH_CONNECTION_ERROR = "WS_AUTH_CONNECTION_ERROR";
export const WS_AUTH_CONNECTION_CLOSED = "WS_AUTH_CONNECTION_CLOSED";
export const WS_AUTH_CONNECTION_CLOSE = "WS_AUTH_CONNECTION_CLOSE";
export const WS_AUTH_GET_ORDERS = "WS_AUTH_GET_ORDERS";
export const WS_AUTH_SEND_ORDERS = "WS_AUTH_SEND_ORDERS";
